=== JOTSR/Dedale/install/.dedale/templates/config.schema.json
{
	"$ref": "#/definitions/Config",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"Config": {
			"additionalProperties": false,
			"description": "Dédale configuration interface",
			"properties": {
				"autoUpdate": {
					"description": "Automatic update of deno Set defaultVersion to the latest",
					"type": "boolean"
				},
				"autoUpgrade": {
					"description": "Automatic upgrade of dédale",
					"type": "boolean"
				},
				"defaultProvider": {
					"description": "Default modules provider url",
					"examples": [
						"https://deno.land/x"
					],
					"type": "string"
				},
				"defaultTemplate": {
					"description": "Default template name of definition",
					"examples": [
						"vscode-mod"
					],
					"type": "string"
				},
				"notifyUpdate": {
					"description": "Notify newer deno version when cli is used",
					"type": "boolean"
				},
				"notifyUpgrade": {
					"description": "Notify newer dédale version when cli is used",
					"type": "boolean"
				},
				"plugins": {
					"additionalProperties": {
						"additionalProperties": false,
						"properties": {
							"activated": {
								"type": "boolean"
							},
							"path": {
								"type": "string"
							}
						},
						"required": [
							"path",
							"activated"
						],
						"type": "object"
					},
					"description": "Plugins installed and activation status Automatically generated Default state of plugins is activated",
					"type": "object"
				},
				"providers": {
					"additionalProperties": {
						"type": "string"
					},
					"description": "List of providers",
					"examples": [
						{
							"deno-std": "https://deno.land/std",
							"deno-x": "https://deno.land/x",
							"esm": "https://esm.sh"
						}
					],
					"type": "object"
				}
			},
			"required": [
				"defaultTemplate",
				"defaultProvider",
				"providers",
				"autoUpdate",
				"notifyUpdate",
				"plugins",
				"autoUpgrade",
				"notifyUpgrade"
			],
			"type": "object"
		}
	}
}

=== JOTSR/Dedale/install/.dedale/dedale.json
{
	"$schema": "./dedale.schema.json",
	"autoUpdate": true,
	"notifyUpdate": true,
	"autoUpgrade": true,
	"notifyUpgrade": true,
	"defaultProvider": "deno.land/x",
	"defaultTemplate": "vscode-mod",
	"plugins": {
		"readme-generator": {
			"path": "https://github.com/dedale/plugins/std/readme-generator/mod.ts",
			"activated": true
		},
		"licence-generator": {
			"path": "https://github.com/dedale/plugins/std/licence-generator/mod.ts",
			"activated": true
		}
	},
	"providers": {
		"deno-x": "deno.land/x",
		"nest.land": "nest.land",
		"github": "github.com",
		"npm": "npm"
	}
}
